Remove libcamera from pipewire
Pipewire pulls in libcamera, which is currently unused. Libcamera
causes many builds to fail because of the FOD creating a different
result when built on different machines.

````
error: hash mismatch importing path '/nix/store/glazsqngfws5m5m8nzq5mxai6rljw1lc-libcamera-0.0.5';
specified: sha256:0vk0r73zczhg58zqrk2fz6wa648bdxrr1pza4vjgglglndx6d4dv
got:       sha256:1gffy40qlljmb74vnb074b1yc8ippd3cp41l7z4rmwyja0i969v0
````

Signed-off-by: Brian McGillion <bmg.avoin@gmail.com>